# **(ADD THE NOTEBOOK NAME HERE)**

## Objectives

* Write your notebook objective here, for example, "Fetch data from Kaggle and save as raw data", or "engineer features for modelling"

## Inputs

* Write down which data or information you need to run the notebook 

## Outputs

* Write here which files, code or artefacts you generate by the end of the notebook 

## Additional Comments

* If you have any additional comments that don't fit in the previous bullets, please state them here. 

## 📉 Goal 1: Reducing Returns (Classification)The goal is to predict which transactions are likely to result in a Return Status (Yes/No) so you can flag risky orders or optimize sizing/descriptions.

## 💎 Goal 2: Predicting High-Value Customers (Regression / Segmentation)The goal is to predict a customer's Future Value or identify high-tier shoppers. We can aggregate data by Customer ID to calculate their total spend and predict it using loyalty metrics.

## 🏷️ Goal 3: Optimizing Discounts (Price Elasticity & Analytics)To optimize discounts, we need to understand the sweet spot where Discount (%) maximizes Quantity or Purchase Amount (₹) without destroying profit margins, especially during a Festival/Sale.


# 🛍️ Festival and Discount DynamicsHypothesis 
* Hypothesis 1: Transactions marked as "Festival/Sale" will have significantly higher "Purchase Amount (₹)" and "Quantity" compared to regular days, but lower average "Review Rating" due to delivery delays.
* Hypothesis 2: High "Discount (%)" levels positively correlate with increased "Quantity" per transaction, but also lead to a higher "Return Status" rate.
🚚 Shipping and Fulfillment Effects.
* Hypothesis 3: Orders with higher "Shipping Charge (₹)" exhibit higher cart abandonment rates (or lower overall "Purchase Amount") unless the "Delivery Speed" is set to express. 
* Hypothesis 4: A "Delivery Time (Days)" exceeding 5 days results in a measurable drop in "Review Rating" for "Online Store" transactions.

👤 Demographics and Category Preferences.
* Hypothesis 5: "Age" and "Gender" significantly influence the "Category" and "Brand" chosen (e.g., younger demographics favor specific trendy brands or online shopping over offline).
* Hypothesis 6: Customers in specific "Location" clusters (e.g., Tier 1 vs Tier 2 cities) show a strong preference for "Online" vs "Offline" shopping channels.


🔁 Customer Loyalty and Retention.
* Hypothesis 7: Customers with an active "Subscription Status" have a higher "Frequency of Purchases" and a higher number of "Previous Purchases" than non-subscribers.
* Hypothesis 8: High "Review Rating" scores on the current purchase are strong predictors of a shorter interval in the "Frequency of Purchases" for the next transaction.

💳 Payment and Sizing Behavior
* Hypothesis 9: Digital "Payment Method" choices (like UPI or Credit Cards) are associated with higher "Purchase Amount (₹)" compared to Cash on Delivery (CoD).
* Hypothesis 10: Certain "Size" and "Color" combinations within specific apparel "Categories" suffer from disproportionately high "Return Status" rates due to sizing inconsistencies.

---

# Change working directory

* We are assuming you will store the notebooks in a subfolder, therefore when running the notebook in the editor, you will need to change the working directory

We need to change the working directory from its current folder to its parent folder
* We access the current directory with os.getcwd()

In [217]:
import os
current_dir = os.getcwd()
current_dir

'c:\\Users\\User\\Desktop\\Data Analysis with AI Course\\Code Institute'

We want to make the parent of the current directory the new current directory
* os.path.dirname() gets the parent directory
* os.chir() defines the new current directory

In [218]:
os.chdir(os.path.dirname(current_dir))
print("You set a new current directory")

You set a new current directory

Confirm the new current directory

In [219]:
current_dir = os.getcwd()
current_dir

'c:\\Users\\User\\Desktop\\Data Analysis with AI Course'

# Read and Transform Data to panda DataFrame

# Section 1 
* Read The Input Data
* Load to Panda's DataFrame

In [220]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
from pathlib import Path

file_name = "dataset/customer_shopping_behavior.csv"
matches = list(Path.cwd().parent.rglob(file_name))

if not matches:
  raise FileNotFoundError(
    f"{file_name} was not found under {Path.cwd()}. "
    "Check that the dataset file is in the project folder."
  )

df = pd.read_csv(matches[0])
print('Dataframe loaded successfully')
print(df.shape)
df.head()

Dataframe loaded successfully
(10000, 26)

,Transaction ID,Customer ID,Purchase Date,Age,Gender,Location,Online/Offline,Online Store,Category,Item Purchased,...,Festival/Sale,Shipping Charge (₹),Delivery Speed,Delivery Time (Days),Subscription Status,Payment Method,Review Rating,Return Status,Previous Purchases,Frequency of Purchases
0,TXN507808,CUST102534,2023-01-01,51,Male,Chennai,Online,Flipkart,Clothing,Kurta,...,NaN,0,Same Day,1,Yes,Cash on Delivery,4,Not Returned,0,Fortnightly
1,TXN503830,CUST101256,2023-01-01,27,Female,Mumbai,Offline,NaN,Clothing,Shirt,...,NaN,0,NaN,0,No,UPI,5,Not Returned,0,Fortnightly
2,TXN501496,CUST100490,2023-01-01,57,Male,Hyderabad,Online,Flipkart,Clothing,Jacket,...,NaN,0,Standard,7,Yes,UPI,3,Not Returned,0,Rarely
3,TXN501538,CUST100500,2023-01-01,22,Female,Pune,Online,Myntra,Clothing,Kurta,...,NaN,0,Standard,6,Yes,Net Banking,4,Not Returned,0,Fortnightly
4,TXN504265,CUST101399,2023-01-01,30,Male,Visakhapatnam,Online,Myntra,Accessories,Cap,...,NaN,99,Express,2,No,Debit Card,4,Not Returned,0,Weekly

---

# Section 1.2
### Explore the Data

Gettingt the dtypes of columns which can be numerical or catogorical

In [221]:
#discovering the shape of the dataset and the column names
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Transaction ID          10000 non-null  object
 1   Customer ID             10000 non-null  object
 2   Purchase Date           10000 non-null  object
 3   Age                     10000 non-null  int64
 4   Gender                  10000 non-null  object
 5   Location                10000 non-null  object
 6   Online/Offline          10000 non-null  object
 7   Online Store            7751 non-null   object
 8   Category                10000 non-null  object
 9   Item Purchased          10000 non-null  object
 10  Brand                   10000 non-null  object
 11  Color                   10000 non-null  object
 12  Size                    8965 non-null   object
 13  Quantity                10000 non-null  int64
 14  Purchase Amount (₹)     10000 non-null  int64
 15  Discount (%)            10000 non-null  int64
 16  Festival/Sale           3212 non-null   object
 17  Shipping Charge (₹)     10000 non-null  int64
 18  Delivery Speed          7751 non-null   object
 19  Delivery Time (Days)    10000 non-null  int64
 20  Subscription Status     10000 non-null  object
 21  Payment Method          10000 non-null  object
 22  Review Rating           10000 non-null  int64
 23  Return Status           10000 non-null  object
 24  Previous Purchases      10000 non-null  int64
 25  Frequency of Purchases  10000 non-null  object
dtypes: int64(8), object(18)
memory usage: 2.0+ MB

---

In [222]:
# view all columns in data set
df.columns

Index(['Transaction ID', 'Customer ID', 'Purchase Date', 'Age', 'Gender',
       'Location', 'Online/Offline', 'Online Store', 'Category',
       'Item Purchased', 'Brand', 'Color', 'Size', 'Quantity',
       'Purchase Amount (₹)', 'Discount (%)', 'Festival/Sale',
       'Shipping Charge (₹)', 'Delivery Speed', 'Delivery Time (Days)',
       'Subscription Status', 'Payment Method', 'Review Rating',
       'Return Status', 'Previous Purchases', 'Frequency of Purchases'],
      dtype='object')

In [223]:
# check data types of each column
df.dtypes

Transaction ID            object
Customer ID               object
Purchase Date             object
Age                        int64
Gender                    object
Location                  object
Online/Offline            object
Online Store              object
Category                  object
Item Purchased            object
Brand                     object
Color                     object
Size                      object
Quantity                   int64
Purchase Amount (₹)        int64
Discount (%)               int64
Festival/Sale             object
Shipping Charge (₹)        int64
Delivery Speed            object
Delivery Time (Days)       int64
Subscription Status       object
Payment Method            object
Review Rating              int64
Return Status             object
Previous Purchases         int64
Frequency of Purchases    object
dtype: object

In [224]:
# check the summary statistics of the dataset
df.describe()

,Age,Quantity,Purchase Amount (₹),Discount (%),Shipping Charge (₹),Delivery Time (Days),Review Rating,Previous Purchases
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,38.278100,1.425100,1889.882000,32.916300,41.49210,3.703600,3.874900,3.211400
std,12.133041,0.761346,2102.301836,21.440617,64.30923,2.726223,0.912871,3.951313
min,18.000000,1.000000,67.000000,0.000000,0.00000,0.000000,1.000000,0.000000
25%,28.000000,1.000000,600.000000,12.000000,0.00000,1.000000,3.000000,0.000000
50%,38.000000,1.000000,1207.000000,33.000000,0.00000,4.000000,4.000000,2.000000
75%,49.000000,2.000000,2376.000000,52.000000,79.00000,6.000000,5.000000,4.000000
max,59.000000,4.000000,22306.000000,70.000000,199.00000,8.000000,5.000000,28.000000

# Conclusion :
### Why ETL Must Come First than EDA

Looking Closely at the raw data 
* Fields like Purchase Date are stored as raw strings (2023-01-01).
* Festival/Sale is flagged as an empty object type in the schema. It likely contains text strings or missing fields that need formatting.
* Frequency of Purchases uses categorical strings like Weekly or Fortnightly.
* Text columns contain whitespace variability (e.g., 'Returned ' vs 'Not Returned').

If we run EDA before fixing these, our charts will break, date-based trends won't plot, and categories will duplicate due to hidden whitespaces.

# Section 2
# ETL Pipeline

### clean, standardise, and structure our dataset into a high-utility format.

In [225]:
# 1. Structural Inspection
print("--- Dataset Shape ---")
print(df.shape)
print("\n--- Data Types & Missing Values ---")
print(df.info())

--- Dataset Shape ---
(10000, 26)

--- Data Types & Missing Values ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Transaction ID          10000 non-null  object
 1   Customer ID             10000 non-null  object
 2   Purchase Date           10000 non-null  object
 3   Age                     10000 non-null  int64
 4   Gender                  10000 non-null  object
 5   Location                10000 non-null  object
 6   Online/Offline          10000 non-null  object
 7   Online Store            7751 non-null   object
 8   Category                10000 non-null  object
 9   Item Purchased          10000 non-null  object
 10  Brand                   10000 non-null  object
 11  Color                   10000 non-null  object
 12  Size                    8965 non-null   object
 13  Quantity                10000 non-null  int64
 14  Purchase Amount (₹)     10000 non-null  int64
 15  Discount (%)            10000 non-null  int64
 16  Festival/Sale           3212 non-null   object
 17  Shipping Charge (₹)     10000 non-null  int64
 18  Delivery Speed          7751 non-null   object
 19  Delivery Time (Days)    10000 non-null  int64
 20  Subscription Status     10000 non-null  object
 21  Payment Method          10000 non-null  object
 22  Review Rating           10000 non-null  int64
 23  Return Status           10000 non-null  object
 24  Previous Purchases      10000 non-null  int64
 25  Frequency of Purchases  10000 non-null  object
dtypes: int64(8), object(18)
memory usage: 2.0+ MB
None

In [226]:
# 2. Check for explicit missing values
print("\n--- Missing Values Count ---")
print(df.isnull().sum())

--- Missing Values Count ---
Transaction ID               0
Customer ID                  0
Purchase Date                0
Age                          0
Gender                       0
Location                     0
Online/Offline               0
Online Store              2249
Category                     0
Item Purchased               0
Brand                        0
Color                        0
Size                      1035
Quantity                     0
Purchase Amount (₹)          0
Discount (%)                 0
Festival/Sale             6788
Shipping Charge (₹)          0
Delivery Speed            2249
Delivery Time (Days)         0
Subscription Status          0
Payment Method               0
Review Rating                0
Return Status                0
Previous Purchases           0
Frequency of Purchases       0
dtype: int64

In [227]:
 # 3. Transform: Clean string columns & strip whitespaces
string_cols = df.select_dtypes(include=['object']).columns
for col in string_cols:
    df[col] = df[col].astype(str).str.strip()

print(string_cols)

Index(['Transaction ID', 'Customer ID', 'Purchase Date', 'Gender', 'Location',
       'Online/Offline', 'Online Store', 'Category', 'Item Purchased', 'Brand',
       'Color', 'Size', 'Festival/Sale', 'Delivery Speed',
       'Subscription Status', 'Payment Method', 'Return Status',
       'Frequency of Purchases'],
      dtype='object')

In [228]:
# 4. Transform: Standardise Datetime
df['Purchase Date'] = pd.to_datetime(df['Purchase Date'])
df['Purchase_Year'] = df['Purchase Date'].dt.year
df['Purchase_Month'] = df['Purchase Date'].dt.month
df['Purchase_DayOfWeek'] = df['Purchase Date'].dt.dayofweek

In [229]:
# 5. Transform: Handle 'Festival/Sale' Missing Values
# Treat true nulls, empty strings, whitespace, and text such as 'nan' as regular days.
festival_sale = df['Festival/Sale'].astype('string').str.strip()
missing_festival_sale = (
    festival_sale.isna()
    | festival_sale.str.lower().isin(['', 'nan', 'none', 'null'])
)
df.loc[missing_festival_sale, 'Festival/Sale'] = 'Regular Day'

print("Missing 'Festival/Sale' values after cleaning:", df['Festival/Sale'].isna().sum())
print("Null-like text values remaining:", df['Festival/Sale'].astype('string').str.strip().str.lower().isin(
    ['', 'nan', 'none', 'null']
).sum())

Missing 'Festival/Sale' values after cleaning: 0
Null-like text values remaining: 0

In [230]:
# 6. Transform: Handle 'Online Store' Missing Values
# Assuming Missing value for 'Online/Offline' as Offline store sale hence missing value can be replaced by 'Local Store'
for i in df.index:
    online_store = df.loc[i, 'Online Store']

    if (
        (pd.isna(online_store) or
         str(online_store).strip().lower() == 'nan')
        and str(df.loc[i, 'Online/Offline']).strip().lower() == 'offline'
    ):
        df.loc[i, 'Online Store'] = 'Not online store'

In [231]:
# 7. Transform: Handle 'Size' Missing Values
df['Size'] = df['Size'].fillna('Unknown')
Size = df['Size'].astype('string').str.strip()
missing_Size = (
    Size.isna()
    | Size.str.lower().isin(['', 'nan', 'none', 'null'])
)
df.loc[missing_Size, 'Size'] = 'Unknown'

In [232]:
# 8. Transform: Handle 'Delivery Speed' Missing Values
# Offline purchases do not require a delivery service, so use 'Hands On'.
delivery_speed = df['Delivery Speed'].astype('string').str.strip()
channel = df['Online/Offline'].astype('string').str.strip().str.lower()
missing_delivery_speed = (
    delivery_speed.isna()
    | delivery_speed.str.lower().isin(['', 'nan', 'none', 'null'])
)
offline_orders = channel.eq('offline')
df.loc[missing_delivery_speed & offline_orders, 'Delivery Speed'] = 'Hands On'

print(
    "Offline orders updated:",
    (missing_delivery_speed & offline_orders).sum()
)
print(
    "Missing Delivery Speed values remaining for offline orders:",
    df.loc[offline_orders, 'Delivery Speed'].isna().sum()
)

Offline orders updated: 2249
Missing Delivery Speed values remaining for offline orders: 0

In [233]:
# 9. Transform: Standardise Targets
df['Is_Returned'] = df['Return Status'].apply(lambda x: 1 if x.lower() == 'returned' else 0)
df['Is_Subscribed'] = df['Subscription Status'].apply(lambda x: 1 if x.lower() == 'yes' else 0)

In [234]:
# 10. Transform: Map Frequency to Ordinal Numbers (For correlation analysis)
freq_map = {'Weekly': 7, 'Fortnightly': 14, 'Monthly': 30, 'Quarterly': 90, 'Rarely': 180}
df['Purchase_Frequency_Days'] = df['Frequency of Purchases'].map(freq_map)

In [ ]:
# 11. Re-check for missing values
print("\n--- Missing Values Count ---")
print(df.isnull().sum())

Transaction ID             0
Customer ID                0
Purchase Date              0
Age                        0
Gender                     0
Location                   0
Online/Offline             0
Online Store               0
Category                   0
Item Purchased             0
Brand                      0
Color                      0
Size                       0
Quantity                   0
Purchase Amount (₹)        0
Discount (%)               0
Festival/Sale              0
Shipping Charge (₹)        0
Delivery Speed             0
Delivery Time (Days)       0
Subscription Status        0
Payment Method             0
Review Rating              0
Return Status              0
Previous Purchases         0
Frequency of Purchases     0
Purchase_Year              0
Purchase_Month             0
Purchase_DayOfWeek         0
Is_Returned                0
Is_Subscribed              0
Purchase_Frequency_Days    0
dtype: int64

In [ ]:
# 12. Load: Save clean baseline
# Locate the project folder from its dataset, then save the output there.
dataset_matches = list(Path.cwd().rglob('dataset/customer_shopping_behavior.csv'))

if not dataset_matches:
    raise FileNotFoundError(
        "The project dataset could not be found from the current working directory."
    )

project_root = dataset_matches[0].parent.parent
output_path = project_root / 'cleaned_customer_shopping_data.csv'
df.to_csv(output_path, index=False)

if not output_path.exists():
    raise FileNotFoundError(f'Output file was not created: {output_path}')

print(f'ETL Pipeline completed successfully! Clean file saved to: {output_path.resolve()}')
print(f'Output file size: {output_path.stat().st_size:,} bytes')

ETL Pipeline completed successfully! Clean file saved to: C:\Users\User\Desktop\Data Analysis with AI Course\Code Institute\vscode-projects\SmartCart_Analytics\SmartCart_Analytics\cleaned_customer_shopping_data.csv
Output file size: 1,884,789 bytes